//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode_2022 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode_2022.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2494
        ///8013
        ///1055
        ///5425
        ///9104
        ///10665
        ///
        ///10642
        ///10677
        ///10300
        ///7374
        ///9085
        ///8508
        ///7569
        ///6214
        ///
        ///5300
        ///5960
        ///8252
        ///5852
        ///4308
        ///9991
        ///6367
        ///
        ///1361
        ///5356
        ///6114
        ///3379
        ///5996
        ///3822
        ///3785
        ///1622
        ///1143
        ///6009
        ///2211
        ///4951
        ///3093
        ///6395
        ///
        ///4892
        ///6648
        ///3022
        ///6063
        ///5436
        ///2174
        ///4264
        ///2004
        ///6444
        ///2926
        ///2651
        ///2749
        ///
        ///17121
        ///17879
        ///11056
        ///15642
        ///
        ///3926
        ///6751
        ///2643
        ///7882
        ///4006
        ///1351
        ///4912
        ///2735
        ///2985
        ///4015
        ///
        ///3043
        ///6923
        ///10352
        ///9998
        ///2470
        ///7346
        ///1077
        ///3024
        ///
        ///21632
        ///34735
        ///
        ///8525
        ///1982
        ///9285
        ///4188
        ///7017
        ///6666
        ///6538
        ///
        ///7019
        ///2696
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B X
        ///B Y
        ///A Y
        ///B Y
        ///B Y
        ///A Y
        ///A X
        ///A Y
        ///C X
        ///A Y
        ///A Y
        ///B Y
        ///B Z
        ///A Y
        ///B Z
        ///B Z
        ///B Z
        ///B Y
        ///A Z
        ///A Y
        ///B X
        ///A Z
        ///A Z
        ///A Z
        ///B Z
        ///A Y
        ///A Z
        ///C X
        ///B Z
        ///A Y
        ///B Z
        ///B Y
        ///A Y
        ///A Y
        ///A Y
        ///A Y
        ///A Z
        ///C X
        ///C Z
        ///A Y
        ///A Y
        ///A X
        ///C X
        ///B Z
        ///B Y
        ///B Y
        ///A Y
        ///C X
        ///A Y
        ///B Z
        ///B Z
        ///A Y
        ///B Y
        ///B Z
        ///A Y
        ///C X
        ///B Y
        ///A Y
        ///A Y
        ///A Y
        ///A Y
        ///B Z
        ///B X
        ///A Y
        ///B Y
        ///A Z
        ///B Y
        ///A Y
        ///C X
        ///A Z
        ///C Z
        ///B Z
        ///B Y
        ///A Y
        ///A Y
        ///B Z
        ///B Y
        ///B Y
        ///B Y
        ///B Z
        ///A X
        ///A Y
        ///A Y
        ///B Z
        ///C X
        ///A Y
        ///B Y
        ///C Z
        ///A Y
        ///C Y
        ///A Y
        ///A Y
        ///C X
        ///A X
        ///A Z
        ///A Y
        ///B Z
        ///A Z
        ///B Z
        ///A Y
        ///B Z
        ///A Y
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QtGHnGlcwQGvHwMHGnnGfRFCJnRBfVVJRVBfCFBh
        ///qsDjzNWhmspNNqVrfjVfjJCbBVfB
        ///DLhPTmNDTzTqzpmzLpswGMHtMgwglcPQMQvSGM
        ///ctwDjvgtltgglHrSHCsQWBBDfS
        ///ZJZdVnmhmfCprnBTfS
        ///dNddhhdPRRdbdNcvwCPCgCctjPlF
        ///MNNDGMWrQsfhtrTnrm
        ///jcvRPRPJdvccRNFNCjLdcwJCSHtHPmzhsSzPHmfhnftnTffH
        ///RddRcjRvZgZNWNgQQb
        ///fPrvhqhRPSfCCfhrqtbtLcmZmtHCtpCFcc
        ///WFQJlTdzgGJVQGWQTzdJcHbQZtLtHmbbZMZHsZQm
        ///JFNlzTBNJGlNPSRhfqRRrN
        ///tdVVgttdDtJJsNPmzdQmjcPP
        ///CBTMmmmbTBHqHMwQcZPWWsWnzbbnzW
        ///CGlLFCTMGvqBGvGvGSRSRfmtRRtgVgrSLS
        ///LHSGJLWZLqHQHpRHRz
        ///bpBPVtpCwPgBCtqq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
    }
}
