//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode_2022 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode_2022.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2494
        ///8013
        ///1055
        ///5425
        ///9104
        ///10665
        ///
        ///10642
        ///10677
        ///10300
        ///7374
        ///9085
        ///8508
        ///7569
        ///6214
        ///
        ///5300
        ///5960
        ///8252
        ///5852
        ///4308
        ///9991
        ///6367
        ///
        ///1361
        ///5356
        ///6114
        ///3379
        ///5996
        ///3822
        ///3785
        ///1622
        ///1143
        ///6009
        ///2211
        ///4951
        ///3093
        ///6395
        ///
        ///4892
        ///6648
        ///3022
        ///6063
        ///5436
        ///2174
        ///4264
        ///2004
        ///6444
        ///2926
        ///2651
        ///2749
        ///
        ///17121
        ///17879
        ///11056
        ///15642
        ///
        ///3926
        ///6751
        ///2643
        ///7882
        ///4006
        ///1351
        ///4912
        ///2735
        ///2985
        ///4015
        ///
        ///3043
        ///6923
        ///10352
        ///9998
        ///2470
        ///7346
        ///1077
        ///3024
        ///
        ///21632
        ///34735
        ///
        ///8525
        ///1982
        ///9285
        ///4188
        ///7017
        ///6666
        ///6538
        ///
        ///7019
        ///2696
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B X
        ///B Y
        ///A Y
        ///B Y
        ///B Y
        ///A Y
        ///A X
        ///A Y
        ///C X
        ///A Y
        ///A Y
        ///B Y
        ///B Z
        ///A Y
        ///B Z
        ///B Z
        ///B Z
        ///B Y
        ///A Z
        ///A Y
        ///B X
        ///A Z
        ///A Z
        ///A Z
        ///B Z
        ///A Y
        ///A Z
        ///C X
        ///B Z
        ///A Y
        ///B Z
        ///B Y
        ///A Y
        ///A Y
        ///A Y
        ///A Y
        ///A Z
        ///C X
        ///C Z
        ///A Y
        ///A Y
        ///A X
        ///C X
        ///B Z
        ///B Y
        ///B Y
        ///A Y
        ///C X
        ///A Y
        ///B Z
        ///B Z
        ///A Y
        ///B Y
        ///B Z
        ///A Y
        ///C X
        ///B Y
        ///A Y
        ///A Y
        ///A Y
        ///A Y
        ///B Z
        ///B X
        ///A Y
        ///B Y
        ///A Z
        ///B Y
        ///A Y
        ///C X
        ///A Z
        ///C Z
        ///B Z
        ///B Y
        ///A Y
        ///A Y
        ///B Z
        ///B Y
        ///B Y
        ///B Y
        ///B Z
        ///A X
        ///A Y
        ///A Y
        ///B Z
        ///C X
        ///A Y
        ///B Y
        ///C Z
        ///A Y
        ///C Y
        ///A Y
        ///A Y
        ///C X
        ///A X
        ///A Z
        ///A Y
        ///B Z
        ///A Z
        ///B Z
        ///A Y
        ///B Z
        ///A Y
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QtGHnGlcwQGvHwMHGnnGfRFCJnRBfVVJRVBfCFBh
        ///qsDjzNWhmspNNqVrfjVfjJCbBVfB
        ///DLhPTmNDTzTqzpmzLpswGMHtMgwglcPQMQvSGM
        ///ctwDjvgtltgglHrSHCsQWBBDfS
        ///ZJZdVnmhmfCprnBTfS
        ///dNddhhdPRRdbdNcvwCPCgCctjPlF
        ///MNNDGMWrQsfhtrTnrm
        ///jcvRPRPJdvccRNFNCjLdcwJCSHtHPmzhsSzPHmfhnftnTffH
        ///RddRcjRvZgZNWNgQQb
        ///fPrvhqhRPSfCCfhrqtbtLcmZmtHCtpCFcc
        ///WFQJlTdzgGJVQGWQTzdJcHbQZtLtHmbbZMZHsZQm
        ///JFNlzTBNJGlNPSRhfqRRrN
        ///tdVVgttdDtJJsNPmzdQmjcPP
        ///CBTMmmmbTBHqHMwQcZPWWsWnzbbnzW
        ///CGlLFCTMGvqBGvGvGSRSRfmtRRtgVgrSLS
        ///LHSGJLWZLqHQHpRHRz
        ///bpBPVtpCwPgBCtqq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-82,3-96
        ///13-95,99-99
        ///4-92,5-93
        ///16-80,16-80
        ///23-36,6-10
        ///82-98,24-83
        ///48-48,47-48
        ///58-81,58-80
        ///14-14,13-98
        ///46-66,45-46
        ///38-73,37-72
        ///46-99,47-47
        ///15-59,6-56
        ///13-54,12-53
        ///60-61,60-71
        ///4-97,2-97
        ///6-94,6-94
        ///47-48,38-48
        ///10-95,10-95
        ///84-87,86-86
        ///51-88,70-84
        ///3-52,51-53
        ///21-55,21-21
        ///55-84,31-56
        ///18-18,19-75
        ///63-76,64-77
        ///44-94,93-98
        ///9-62,2-4
        ///29-34,28-33
        ///14-97,15-98
        ///10-56,10-56
        ///3-92,4-93
        ///44-92,45-93
        ///7-73,6-72
        ///12-96,12-12
        ///17-83,82-83
        ///8-94,9-97
        ///1-96,2-96
        ///82-93,4-81
        ///45-62,3-62
        ///91-96,3-81
        ///69-8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [H]         [H]         [V]    
        ///    [V]         [V] [J]     [F] [F]
        ///    [S] [L]     [M] [B]     [L] [J]
        ///    [C] [N] [B] [W] [D]     [D] [M]
        ///[G] [L] [M] [S] [S] [C]     [T] [V]
        ///[P] [B] [B] [P] [Q] [S] [L] [H] [B]
        ///[N] [J] [D] [V] [C] [Q] [Q] [M] [P]
        ///[R] [T] [T] [R] [G] [W] [F] [W] [L]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 3 from 3 to 7
        ///move 4 from 1 to 9
        ///move 5 from 6 to 3
        ///move 6 from 9 to 8
        ///move 2 from 9 to 5
        ///move 4 from 3 to 7
        ///move 1 from 3 to 6
        ///move 3 from 5 to 7
        ///move 1 from 2 to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grvrnvrnnjljbjqjpqjjvhhzwwrbwwbblrltrrpbbbbqnnqbbbbsvbvmbvmbbrsrqrzrllwbbbqzqrqnqrnrjnnjccdggwqqhrrjcjmjmllgrlglhlclmlvlvsshwwsggmfmdfddgdfftrrczrcczhzppgdgrdggghmmdwwqgggslglfgfcgccmjcjwjrwjrjcrjjsgjjvddpwpgpbbgwbgwwhnhfftbffhpfphhfqfrqfrfnfpprvrsrhrfrllfhhrsrhssvfsvsnvsnsswtwtlthllrjjwddtggzczgcchwcwppfbbdvdrdzrdrvrwwsbsfbssqfsfjsjcscttlztllgjjlbbdsdtssvvvwlvlqqnhqqtdqtddjcdcjjpbphhgtgtqtzqqzhqqtgtvtmvtvrvqrvvfmfmppzzbwwnddzttfpfrrlddbppfqppnwnswwdhwdwjjqljqqthtnhnddgmgcmgcmgcmmfmfttrzzfdzztllmjlllgcgbbcq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
    }
}
